env:
  browser: true
  commonjs: true
  es6: true
extends: ['eslint:recommended', 'plugin:react/recommended']
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  react/jsx-uses-vars: 1
  react/prop-types: [1, { ignore: [children] }]
  key-spacing: 1
  curly: 0
  consistent-return: 0
  space-infix-ops: 1
  camelcase: 0
  no-spaced-func: 1
  no-alert: 1
  comma-spacing: 1
  eqeqeq: 1
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - double
  # semi:
  #   - error
  #   - always
  no-console: 0
globals:
    process: true
    __dirname: true
    _testColors: true
    Enzyme: true

